remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Federation
logo: /img/epic_logo.png
description: Explore & build your way home in this 3D time-manipulation production puzzler, coming soon to Mac & PC.
show_downloads: true
# https://github.com/pages-themes/minimal#usage